### ISSUE TITLE
TaLK need to divide by the area of span?

### ISSUE THREAD

**Issue by gaopengcuhk** [lioutasb/TaLKConvolutions#2]
Is it possible to divide the output of TaLK to the area of span?

area = (left_offset + right_offset) * kernel
output = integral / area

**Comment by lioutasb** [comment]
We tried normalizing by the size of the summed area (effectively making it an adaptive average pooling) but this normalization made the training unstable. We believe this is because we optimize the parameters ᾶ^l and ᾶ^r for both the optimal window size as well as bringing the magnitude of the representation down.

**Comment by gaopengcuhk** [comment]
Thank you for your response.
However, without normalization, the output value will be very large as the window size increase.
