### ISSUE TITLE
The talkconv_cuda.py

### ISSUE THREAD

**Issue by WorryfreeY** [lioutasb/TaLKConvolutions#5]
I can't find the talkconv_cuda.py in the code. Where is it?

**Comment by lioutasb** [comment]
I assume you are getting an error when trying to import [this line](https://github.com/lioutasb/TaLKConvolutions/blob/master/talkconv/talkconv_fairseq/talkconv_function.py#L2). You have to compile and install the custom CUDA library as described [here](https://github.com/lioutasb/TaLKConvolutions#efficient-cuda-kernels) in order to use TaLK convolutions.
